import { TemplateDesign } from "@/lib/editor/types";

export const awsVerifyTemplate: TemplateDesign = {
  version: "2.0",
  globalStyles: {
    contentBackgroundColor: "#ffffff",
    contentWidth: 600,
    responsiveDesign: true,
  },
  stripes: [
    {
      id: "aws-stripe-main",
      type: "stripe",
      label: "Main Content",
      props: {
        backgroundColor: "transparent",
        paddingTop: 0,
        paddingBottom: 0,
        fullWidth: false,
      },
      structures: [
        {
          id: "aws-struct-body",
          type: "structure",
          props: {
            backgroundColor: "#eeeeee",
            paddingTop: 20,
            paddingBottom: 0,
            paddingLeft: 20,
            paddingRight: 20,
            marginTop: 0,
            marginBottom: 0,
            marginLeft: 0,
            marginRight: 0,
            columnGap: 0,
          },
          columns: [
            {
              id: "aws-col-white-box",
              widthRatio: 1,
              props: {
                paddingTop: 0,
                paddingBottom: 0,
                paddingLeft: 0,
                paddingRight: 0,
                verticalAlign: "top",
                backgroundColor: "#ffffff",
              },
              blocks: [
                {
                  id: "aws-block-logo",
                  type: "image",
                  props: {
                    src: "https://www.kaizenanalytix.com/wp-content/uploads/2024/09/aws-white.png",
                    alt: "AWS Logo",
                    width: 75,
                    height: "auto",
                    alignDesktop: "center",
                    align: "center", // legacy
                    blockBackgroundColor: "#252f3d",
                    paddingDesktop: { top: 20, right: 0, bottom: 20, left: 0, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-heading",
                  type: "text",
                  props: {
                    content: "Verify your email address",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 20,
                    fontWeight: "bold",
                    color: "#333333",
                    alignDesktop: "left",
                    lineHeightDesktop: 1.2,
                    paddingDesktop: { top: 25, right: 35, bottom: 15, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-intro",
                  type: "text",
                  props: {
                    content: "Thanks for starting the new AWS account creation process. We want to make sure it's really you. Please enter the following verification code when prompted. If you don't want to create an account, you can ignore this message.",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 14,
                    fontWeight: "normal",
                    color: "#333333",
                    alignDesktop: "left",
                    lineHeightDesktop: "24px",
                    paddingDesktop: { top: 24, right: 35, bottom: 14, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-code-label",
                  type: "text",
                  props: {
                    content: "Verification code",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 14,
                    fontWeight: "bold",
                    color: "#333333",
                    alignDesktop: "center",
                    paddingDesktop: { top: 0, right: 35, bottom: 0, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-code-value",
                  type: "text",
                  props: {
                    content: "596853",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 36,
                    fontWeight: "bold",
                    color: "#333333",
                    alignDesktop: "center",
                    paddingDesktop: { top: 10, right: 35, bottom: 10, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-code-note",
                  type: "text",
                  props: {
                    content: "(This code is valid for 10 minutes)",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 14,
                    fontWeight: "normal",
                    color: "#333333",
                    alignDesktop: "center",
                    paddingDesktop: { top: 0, right: 35, bottom: 25, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-divider",
                  type: "divider",
                  props: {
                    color: "#eaeaea",
                    lineWidth: 1,
                    widthDesktop: 100,
                    borderStyle: "solid",
                    paddingDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
                {
                  id: "aws-block-security",
                  type: "text",
                  props: {
                    content: "Amazon Web Services will never email you and ask you to disclose or verify your password, credit card, or banking account number.",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 14,
                    fontWeight: "normal",
                    color: "#333333",
                    alignDesktop: "left",
                    lineHeightDesktop: "24px",
                    paddingDesktop: { top: 25, right: 35, bottom: 25, left: 35, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
              ],
            },
          ],
        },
        {
          id: "aws-struct-footer",
          type: "structure",
          props: {
            backgroundColor: "#eeeeee",
            paddingTop: 0,
            paddingBottom: 20,
            paddingLeft: 20,
            paddingRight: 20,
            marginTop: 0,
            marginBottom: 0,
            marginLeft: 0,
            marginRight: 0,
            columnGap: 0,
          },
          columns: [
            {
              id: "aws-col-footer",
              widthRatio: 1,
              props: {
                paddingTop: 0,
                paddingBottom: 0,
                paddingLeft: 0,
                paddingRight: 0,
                verticalAlign: "top",
                backgroundColor: "transparent",
              },
              blocks: [
                {
                  id: "aws-block-footer-text",
                  type: "text",
                  props: {
                    content: "This message was produced and distributed by Amazon Web Services, Inc., 410 Terry Ave. North, Seattle, WA 98109. © 2022, Amazon Web Services, Inc.. All rights reserved. AWS is a registered trademark of <a href='https://amazon.com' style='color: #2754C5; text-decoration: underline;'>Amazon.com</a>, Inc. View our <a href='https://amazon.com' style='color: #2754C5; text-decoration: underline;'>privacy policy</a>.",
                    fontFamily: "Arial, sans-serif",
                    fontSizeDesktop: 12,
                    fontWeight: "normal",
                    color: "#333333",
                    alignDesktop: "left",
                    paddingDesktop: { top: 24, right: 20, bottom: 0, left: 20, linked: false },
                    marginDesktop: { top: 0, right: 0, bottom: 0, left: 0, linked: true },
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
